spring:
  application:
    name: todoapp

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: winstead12!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
        jdbc:
          datasource: INFO
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      zaxxer:
        hikari: INFO